Repository netuitive-community-packages/netuitive-packages-windows, pull requests merged in 2018-03, with the labels that each got.

#27 Fixing memory utilization widget
  README.md
  dashboards/windows.summary.json
Labels: bug

#28 Cleaning up heartbeat policy title and description
  README.md
  policies/windows.-.agent.appears.to.be.down.json
Labels: improvement

#29 Improvement/travis cli validation
  .travis.yml
  README.md
Labels: enhancement
